#!/usr/bin/python3
# Write UTF-8 text to frame buffer, works with python 2 or 3

from __future__ import print_function
import os, sys, getopt, fbui

usage = """
Usage:

    fbask [options] "question"

Ask a question, get an answer. Exit status is 0 for Yes, 1 for No, anything else for error.

Options are:

    -n "string"             - string for "No"
    -y "string"             - sring for "Yes"
"""

no = "No"
yes = "Yes"

try:
    opts, args = getopt.getopt(sys.argv[1:],":n:y:")

    if not args: raise Exception("Must provide a question.")

    for opt, arg in opts:
        if opt == "-n": notext = arg
        elif opt == "-y": yestext = arg
        else: raise Exception("Invalid option '%s'" % opt)

except Exception as e:
    print (str(e),"\n",usage,file = sys.stderr)
    quit(2)

ui = fbui.ui()
answer = ui.ask(" ".join(args), yestext=yestext, notext=notext)
quit(0 if answer else 1)
