#!/usr/bin/python3
import os, sys, getopt, fb
from pgmagick import *

usage="""
Usage:

    fbcap [options] filename

Capture frame buffer to specified image file. The file name must specify the
image type, i.e. ends with ".png", ".jpg", ".gif", etc.

Options are:

    -d device       - framebuffer device, default is "/dev/fb0"
"""

device="/dev/fb0"

try:
    opts, args = getopt.getopt(sys.argv[1:],"d:")
    for opt, arg in opts:
        if opt == "-d": device = arg
        else: raise Exception("Invalid option '%s'" % opt)
    if len(args) != 1: raise Exception("Expected a filename")

except Exception as e:
    print (str(e),usage, file=sys.stderr)
    quit(1)

fb = fb.framebuffer(device=device)
im = Image(Blob(fb.unpack()), Geometry(fb.width, fb.height), 8, "RGB")
print("Writing %s..." % args[0])
im.write(args[0])
