#!/usr/bin/python3
# Clear frame buffer, works with python 2 or 3

from __future__ import print_function
import os, sys, getopt, fb, screen

usage="""
Usage:

    fbclear [options]

Clear the frame buffer.

Options are:

    -c color                - background color, default is "black"
    -d device               - framebuffer device, default is "/dev/fb0"
"""

color="black"
device="/dev/fb0"

try:

    opts, args = getopt.getopt(sys.argv[1:],"c:d:")
    for opt, arg in opts:
        if   opt == "-c": color=arg.lower()
        elif opt == "-d": device=arg
        else: raise Exception("Invalid option '%s'" % opt)
    if len(args): raise Exception("Unexpected argument '%s'" % ' '.join(args))

except Exception as e:

    print (str(e),usage, file=sys.stderr)
    quit(1)

f=fb.framebuffer(device=device)
i=screen.screen(width=f.width, height=f.height, fg=color, bg=color)
f.pack(i.rgb())
