#!/usr/bin/python2
from __future__ import print_function
import os, sys, getopt, fbclear

usage="""
Usage:

    fbclear [options]

Clear the frame buffer.

Options are:

    -c color                - background color, default is "black"
    -d device               - framebuffer device, default is "/dev/fb0"
"""

color="black"
device="/dev/fb0"

try:

    opts, args = getopt.getopt(sys.argv[1:],"c:d:")
    for opt, arg in opts:
        if   opt == "-c": color=arg.lower()
        elif opt == "-d": device=arg
        else: raise Exception("Invalid option '%s'" % opt)
    if len(args): raise Exception("Unexpected argument '%s'" % ' '.join(args))

except Exception as e:

    print (str(e),usage, file=sys.stderr)
    quit(1)

fbclear.fbclear(color, device)
