#!/usr/bin/python3
"""
Usage:

    fbclear [options]

Clear the frame buffer.

Options are:

    -c color                - background color, default is "black"
    -d device               - framebuffer device, default is "/dev/fb0"
"""

import os, sys, getopt

try: import screen                 # works if this executable is in the fbtools directory
except: from fbtools import screen # works if fbtools is installed as a package

color="black"
device="/dev/fb0"

try:

    opts, args = getopt.getopt(sys.argv[1:],"c:d:")
    for opt, arg in opts:
        if   opt == "-c": color = arg.lower()
        elif opt == "-d": device = arg
        else: raise Exception("Invalid option '%s'" % opt)
    if len(args): raise Exception("Unexpected argument '%s'" % ' '.join(args))

except Exception as e:

    print (str(e), "\n", __doc__, file=sys.stderr)
    quit(1)

screen.Screen(fbdev=device, bg=color).display()
